### PR TITLE
Fixes to clazy warnings

### LINKED ISSUE #47: String optimizations
https://blog.qt.io/blog/2014/06/13/qt-weekly-13-qstringliteral/
https://woboq.com/blog/qstringliteral.html
http://catchchallenger.first-world.info/wiki/Benchmark_for_conception#String
http://code.qt.io/cgit/qt/qtbase.git/commit/?id=bf1df558461f21827eaad9d5d9541def784980a2

TL;DR: Use QString() for empty strings, use QLatin1String unless a QString object needs to be created otherwise it blows up binary size.

### PR DESCRIPTION
**Pull request by iBeliever**
Fixes all level 0, 1, and 2 warnings (being careful of level 2 false positives and pitfalls).

Fixes #47

### CODE REVIEW

**Comment by plfiorini** [comment]
We don't need 99% of KCoreAddons all we need is the formatting functions.

File: compositor/sessionmanager/sessionmanager.cpp [hunk 1]
```diff
@@ -201,15 +193,9 @@ bool SessionManager::canPowerOff()
     return m_powerManager->capabilities() & PowerManager::PowerOff;
 }
 
-bool SessionManager::canRestart()
-{
-    return m_powerManager->capabilities() & PowerManager::Restart;
-}
+bool SessionManager::canRestart() { return m_powerManager->capabilities() & PowerManager::Restart; }
```
Comment (plfiorini) [inline compositor/sessionmanager/sessionmanager.cpp]: i'm concerned about this formatting, it's not very readable and not in the Qt style

Comment (iBeliever) [inline compositor/sessionmanager/sessionmanager.cpp]: Ok - will change my clangformat style.

File: compositor/sessionmanager/sessionmanager.cpp [hunk 2]
```diff
@@ -320,9 +285,6 @@ void SessionManager::requestHybridSleep()
...
 }
 
-void SessionManager::cancelShutdownRequest()
-{
-    Q_EMIT shutdownRequestCanceled();
-}
+void SessionManager::cancelShutdownRequest() { Q_EMIT shutdownRequestCanceled(); }
 
-#include "moc_sessionmanager.cpp"
+#include "sessionmanager.moc"
```
Comment (plfiorini) [inline compositor/sessionmanager/sessionmanager.cpp]: moc creates moc_sessionmanager.cpp not sessionmanager.moc

Comment (iBeliever) [inline compositor/sessionmanager/sessionmanager.cpp]: It works fine without including the `moc_*.cpp` files. However, it's necessary to include the `*.moc` here because `Q_OBJECT` is used in the C++ file. See http://stackoverflow.com/q/34928933.

Comment (plfiorini) [inline compositor/sessionmanager/sessionmanager.cpp]: it's the same, just a different name.
automoc creates moc_*.cpp and ".moc for code with implementation only (not header)

https://cmake.org/cmake/help/v3.0/manual/cmake-qt.7.html#manual:cmake-qt(7)

Comment (iBeliever) [inline compositor/sessionmanager/sessionmanager.cpp]: Right, but if Q_OBJECT was used in a C++ file, it's going to be named `*.moc` per the link you shared. If it's not included in a source file, it'll be compiled automatically, so we don't normally need to add it at the bottom of our source files.

However... when Q_OBJECT is used in a C++ file like I'm doing here, without the include or when including `moc_*.cpp`,  I get:

```
[  9%] Automatic moc and rcc for target hawaii
AUTOGEN: error: /home/mspencer/Developer/qmlos/shell/compositor/sessionmanager/sessionmanager.cpp: The file contains a Q_OBJECT macro, but does not include "sessionmanager.moc" !

make[2]: *** [compositor/CMakeFiles/hawaii_automoc.dir/build.make:58: compositor/CMakeFiles/hawaii_automoc] Error 1
make[1]: *** [CMakeFiles/Makefile2:329: compositor/CMakeFiles/hawaii_automoc.dir/all] Error 2
```

So... we don't normally need to include the moc files ourselves, unless `Q_OBJECT` is used in a C++ file, in which case moc requires we include the file named `*.moc`.

Comment (plfiorini) [inline compositor/sessionmanager/sessionmanager.cpp]: weird other files include moc_*.cpp

Comment (iBeliever) [inline compositor/sessionmanager/sessionmanager.cpp]: Yeah, it's not necessary in those cases. From the link you shared:

> The moc file may be included by the user in the C++ implementation file with a preprocessor #include. If it is not so included, it will be added to a separate file which is compiled into the target.

Comment (plfiorini) [inline compositor/sessionmanager/sessionmanager.cpp]: "If a Q_OBJECT or Q_GADGET macro is found in a header file, moc will be run on the file. The result will be put into a file named according to moc_<basename>.cpp. If the macro is found in a C++ implementation file, the moc output will be put into a file named according to <basename>.moc, following the Qt conventions."

this means if you have your declaration in a .h file the moc file is called moc_*.cpp but if both declaration and implementation are in the .cpp file moc wants *.moc like in some plugin.cpp

Comment (plfiorini) [inline compositor/sessionmanager/sessionmanager.cpp]: on the other hand automoc will probably create a .cpp file with all the moc stuff if we don't include at all

Comment (iBeliever) [inline compositor/sessionmanager/sessionmanager.cpp]: So there's a Q_OBJECT in both the .h and now the .cpp. So what is happening is there's both a moc_sessionmanager.cpp and a sessionmanager.moc file:

```
$ ls compositor/*moc*
compositor/hawaii_automoc.cpp     compositor/moc_loginmanagerbackend.cpp  compositor/moc_screensaver.cpp          compositor/processlauncheradaptor.moc_parameters
compositor/moc_application.cpp    compositor/moc_loginmanager.cpp         compositor/moc_sessionmanager.cpp       compositor/sessionmanager.moc
compositor/moc_authenticator.cpp  compositor/moc_powermanagerbackend.cpp  compositor/moc_systemdpowerbackend.cpp
compositor/moc_fakebackend.cpp    compositor/moc_powermanager.cpp         compositor/moc_upowerpowerbackend.cpp
compositor/moc_logindbackend.cpp  compositor/moc_processlauncher.cpp      compositor/processlauncheradaptor.moc```

Here's where `moc_sessionmanager.cpp` is automatically being compiled:

```
$ cat compositor/hawaii_automoc.cpp   
/* This file is autogenerated, do not edit*/
#include "moc_fakebackend.cpp"
#include "moc_powermanagerbackend.cpp"
#include "moc_systemdpowerbackend.cpp"
#include "moc_upowerpowerbackend.cpp"
#include "moc_sessionmanager.cpp"
```

If I have both `moc_sessionmanager.cpp` and `sessionmanager.moc` being included at the bottom of the sessionmanager.cpp file, then `moc_sessionmanager is not included in hawaii_automoc.cpp`:

```
$  cat compositor/hawaii_automoc.cpp                                                                                   
/* This file is autogenerated, do not edit*/
#include "moc_fakebackend.cpp"
#include "moc_powermanagerbackend.cpp"
#include "moc_systemdpowerbackend.cpp"
#include "moc_upowerpowerbackend.cpp"
```

So, we must include the .moc file or the build will fail. We can optionally include moc_.cpp files, but since they're automatically compiled, I'd prefer not including them as its unnecessary.

File: compositor/sessionmanager/sessionmanager.cpp (hunk 1 above)
Comment (iBeliever) [inline compositor/sessionmanager/sessionmanager.cpp]: Reformatted using the Qt clang-format in repotools.

**Comment by iBeliever** [comment]
@plfiorini This is ready for you to review now.

File: compositor/sessionmanager/sessionmanager.cpp (hunk 2 above)
Comment (plfiorini) [inline compositor/sessionmanager/sessionmanager.cpp]: Ok i didn't notice that!

**Comment by plfiorini** [comment]
@iBeliever ok going to take a look as soon as i go home

**Comment by plfiorini** [comment]
@iBeliever there are errors with gcc:

`
[  2%] Automatic moc and rcc for target HawaiiSigWatch
Generating moc source moc_sigwatch.cpp
Generating moc compilation HawaiiSigWatch_automoc.cpp
[  2%] Built target HawaiiSigWatch_automoc
Scanning dependencies of target HawaiiSigWatch
[  4%] Building CXX object 3rdparty/sigwatch/CMakeFiles/HawaiiSigWatch.dir/sigwatch.cpp.o
In file included from /home/plfiorini/git/qmlos/shell/3rdparty/sigwatch/sigwatch_p.h:3:0,
                 from /home/plfiorini/git/qmlos/shell/3rdparty/sigwatch/sigwatch.cpp:34:
/usr/include/qt/QtCore/5.7.0/QtCore/private/qobject_p.h: In instantiation of ‘static void QtPrivate::QPrivateSlotObject<Func, Args, R>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) [with Func = void (UnixSignalWatcherPrivate::*)(int); Args = QtPrivate::List<int>; R = void]’:
/usr/include/qt/QtCore/5.7.0/QtCore/private/qobject_p.h:319:59:   required from ‘QtPrivate::QPrivateSlotObject<Func, Args, R>::QPrivateSlotObject(Func) [with Func = void (UnixSignalWatcherPrivate::*)(int); Args = QtPrivate::List<int>; R = void]’
/usr/include/qt/QtCore/5.7.0/QtCore/private/qobject_p.h:347:9:   required from ‘static QMetaObject::Connection QObjectPrivate::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, const typename QtPrivate::FunctionPointer<Func2>::Object*, Func2, Qt::ConnectionType) [with Func1 = void (QSocketNotifier::*)(int, QSocketNotifier::QPrivateSignal); Func2 = void (UnixSignalWatcherPrivate::*)(int); typename QtPrivate::FunctionPointer<Func>::Object = QSocketNotifier; typename QtPrivate::FunctionPointer<Func2>::Object = UnixSignalWatcherPrivate]’
/home/plfiorini/git/qmlos/shell/3rdparty/sigwatch/sigwatch.cpp:50:93:   required from here
/usr/include/qt/QtCore/5.7.0/QtCore/private/qobject_p.h:304:9: error: switch missing default case [-Werror=switch-default]
         switch (which) {
         ^~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [3rdparty/sigwatch/CMakeFiles/HawaiiSigWatch.dir/build.make:63: 3rdparty/sigwatch/CMakeFiles/HawaiiSigWatch.dir/sigwatch.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:169: 3rdparty/sigwatch/CMakeFiles/HawaiiSigWatch.dir/all] Error 2
make: *** [Makefile:161: all] Error 2
`

**Comment by plfiorini** [comment]
Originally UnixSignalWatcherPrivate was a QObject, if you want to make it a QObjectPrivate declare the slot on UnixSignalWatcher with Q_DECLARE_PRIVATE_SLOT(d_func(), void _q_notify(int sockfd)) and have a void UnixSignalWatcherPrivate::_q_notify(int sockfd) method.

**Comment by plfiorini** [comment]
@iBeliever ping

**Comment by plfiorini** [comment]
Force pushed a rebase

**Comment by plfiorini** [comment]
@iBeliever Build fixed, now I'm merging your PR.
